import React from 'react';
import KidTalesLegalLayout from './KidTalesLegalLayout';

const englishContent = `
      <h1>KidTales AI – Terms of Use</h1>
      <p><strong>Last Updated:</strong> June 7, 2026<br />
      <strong>Developer:</strong> İbrahim Atmaca</p>

      <p>
        These Terms of Use ("Terms") govern your access to and use of KidTales AI
        ("we", "our", "the App"). By downloading, accessing, or using the App,
        you agree to these Terms.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        If you do not agree with these Terms, please do not use the App. If the
        App is used by a child, a parent or legal guardian is responsible for
        reviewing these Terms and supervising use of the App.
      </p>

      <h2>2. Service Description</h2>
      <p>
        KidTales AI provides AI-assisted story generation for children. Users may
        enter simple prompts such as character names, objects, themes, or story
        ideas, and the App generates fictional story content based on those
        prompts.
      </p>

      <h2>3. Eligibility and Parental Supervision</h2>
      <p>
        KidTales AI is designed to be child-friendly. Children under 13 should
        use the App only with the involvement and supervision of a parent or
        legal guardian. Parents and guardians are responsible for ensuring that
        prompts entered into the App are appropriate.
      </p>

      <h2>4. User Conduct</h2>
      <p>You agree not to use the App to create, request, or submit content that:</p>
      <ul>
        <li>Contains personal information about a child or another person</li>
        <li>Is unlawful, harmful, abusive, hateful, violent, or sexual</li>
        <li>Violates intellectual property, privacy, or other rights</li>
        <li>Attempts to misuse, disrupt, reverse engineer, or overload the App</li>
      </ul>

      <h2>5. AI Content Disclaimer</h2>
      <p>
        Stories generated by the App are fictional and created automatically
        using AI technology. AI-generated content may occasionally be incomplete,
        inaccurate, unexpected, or unsuitable. Parents and guardians should
        review generated stories before sharing them with children.
      </p>
      <p>
        The App does not provide medical, legal, educational, psychological, or
        professional advice.
      </p>

      <h2>6. Intellectual Property</h2>
      <p>
        The App, including its design, software, branding, interface, and related
        materials, is owned by İbrahim Atmaca or licensed to us and is protected
        by applicable intellectual property laws.
      </p>
      <p>
        You remain responsible for the prompts you submit. You may use generated
        stories for personal, non-commercial purposes, provided your use complies
        with these Terms and applicable laws.
      </p>

      <h2>7. In-App Purchases and Subscriptions</h2>
      <p>
        KidTales AI may offer premium features through in-app purchases or
        auto-renewable subscriptions using Apple's StoreKit framework.
      </p>
      <ul>
        <li>Payments are charged to your Apple ID account by Apple.</li>
        <li>
          Subscriptions automatically renew unless cancelled at least 24 hours
          before the end of the current period.
        </li>
        <li>
          You can manage or cancel subscriptions in your Apple ID account
          settings.
        </li>
        <li>
          Refunds, billing issues, renewals, and cancellations are handled by
          Apple according to Apple's policies.
        </li>
        <li>
          Prices and available premium features may change, subject to Apple's
          App Store rules and any required user notice.
        </li>
      </ul>

      <h2>8. Apple Standard EULA</h2>
      <p>
        KidTales AI is licensed to you under
        <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener noreferrer">
          Apple's Standard End User License Agreement
        </a>
        unless a custom agreement is required by applicable law. These Terms
        supplement the Apple Standard EULA where permitted.
      </p>

      <h2>9. Privacy</h2>
      <p>
        Your use of the App is also governed by the KidTales AI Privacy Policy,
        available at
        <a href="https://ibrahimatmaca.github.io/kidtales-privacy" target="_blank" rel="noopener noreferrer">
          https://ibrahimatmaca.github.io/kidtales-privacy
        </a>.
      </p>

      <h2>10. Termination</h2>
      <p>
        KidTales AI does not require account registration. We may suspend or
        limit access to the App if the App is misused, if these Terms are
        violated, or if required for legal, safety, or technical reasons.
      </p>

      <h2>11. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, the App is provided "as is" and
        "as available." We are not liable for indirect, incidental, special, or
        consequential damages arising from use of the App or reliance on
        AI-generated content.
      </p>

      <h2>12. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the Republic of Turkey, without
        prejudice to any mandatory consumer protection rights that may apply in
        your country or region.
      </p>

      <h2>13. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Updated Terms will be
        published on this page and become effective when posted.
      </p>
      <p>
        The latest version is available at
        <a href="https://ibrahimatmaca.github.io/kidtales-terms" target="_blank" rel="noopener noreferrer">
          https://ibrahimatmaca.github.io/kidtales-terms
        </a>.
      </p>

      <h2>14. Contact Information</h2>
      <p>
        For questions about these Terms, please contact:
        <br />
        <strong>
          Email:
          <a href="mailto:ibrahim.atmaca61@hotmail.com">ibrahim.atmaca61@hotmail.com</a>
        </strong>
      </p>
`;

const turkishContent = `
      <h1>KidTales AI – Kullanım Şartları</h1>
      <p><strong>Son Güncelleme:</strong> 7 Haziran 2026<br />
      <strong>Geliştirici:</strong> İbrahim Atmaca</p>

      <p>
        Bu Kullanım Şartları ("Şartlar"), KidTales AI ("biz", "uygulama")
        erişiminizi ve kullanımınızı düzenler. Uygulamayı indirerek, erişerek
        veya kullanarak bu Şartları kabul etmiş olursunuz.
      </p>

      <h2>1. Şartların Kabulü</h2>
      <p>
        Bu Şartları kabul etmiyorsanız lütfen uygulamayı kullanmayın. Uygulama
        bir çocuk tarafından kullanılıyorsa, ebeveyn veya yasal vasi bu Şartları
        incelemekten ve kullanımı gözetmekten sorumludur.
      </p>

      <h2>2. Hizmet Açıklaması</h2>
      <p>
        KidTales AI, çocuklar için yapay zekâ destekli hikâye üretimi sunar.
        Kullanıcılar karakter isimleri, nesneler, temalar veya hikâye fikirleri
        gibi basit girdiler yazabilir; uygulama bu girdilere göre kurgusal
        hikâye içeriği oluşturur.
      </p>

      <h2>3. Uygunluk ve Ebeveyn Gözetimi</h2>
      <p>
        KidTales AI çocuk dostu olacak şekilde tasarlanmıştır. 13 yaş altındaki
        çocuklar uygulamayı yalnızca ebeveyn veya yasal vasi katılımı ve
        gözetimiyle kullanmalıdır. Uygulamaya girilen metinlerin uygunluğundan
        ebeveynler ve vasiler sorumludur.
      </p>

      <h2>4. Kullanıcı Davranışı</h2>
      <p>Uygulamayı aşağıdaki içerikleri oluşturmak, istemek veya göndermek için kullanmamayı kabul edersiniz:</p>
      <ul>
        <li>Bir çocuk veya başka bir kişi hakkında kişisel bilgi içeren içerikler</li>
        <li>Hukuka aykırı, zararlı, taciz edici, nefret içeren, şiddet içeren veya cinsel içerikler</li>
        <li>Fikri mülkiyet, gizlilik veya diğer hakları ihlal eden içerikler</li>
        <li>Uygulamayı kötüye kullanmaya, bozmaya, tersine mühendislik yapmaya veya aşırı yüklemeye yönelik eylemler</li>
      </ul>

      <h2>5. Yapay Zekâ İçeriği Hakkında Uyarı</h2>
      <p>
        Uygulama tarafından üretilen hikâyeler kurgusaldır ve yapay zekâ
        teknolojisiyle otomatik olarak oluşturulur. Yapay zekâ içerikleri zaman
        zaman eksik, hatalı, beklenmedik veya uygunsuz olabilir. Ebeveynler ve
        vasiler, üretilen hikâyeleri çocuklarla paylaşmadan önce gözden
        geçirmelidir.
      </p>
      <p>
        Uygulama tıbbi, hukuki, eğitimsel, psikolojik veya profesyonel tavsiye
        sağlamaz.
      </p>

      <h2>6. Fikri Mülkiyet</h2>
      <p>
        Uygulamanın tasarımı, yazılımı, markası, arayüzü ve ilgili materyalleri
        İbrahim Atmaca'ya aittir veya tarafımıza lisanslanmıştır ve geçerli
        fikri mülkiyet yasalarıyla korunur.
      </p>
      <p>
        Gönderdiğiniz girdilerden siz sorumlusunuz. Üretilen hikâyeleri bu
        Şartlara ve geçerli yasalara uygun olmak kaydıyla kişisel ve ticari
        olmayan amaçlarla kullanabilirsiniz.
      </p>

      <h2>7. Uygulama İçi Satın Almalar ve Abonelikler</h2>
      <p>
        KidTales AI, Apple StoreKit üzerinden uygulama içi satın alma veya
        otomatik yenilenen aboneliklerle premium özellikler sunabilir.
      </p>
      <ul>
        <li>Ödemeler Apple tarafından Apple ID hesabınız üzerinden tahsil edilir.</li>
        <li>
          Abonelikler, mevcut dönem bitmeden en az 24 saat önce iptal edilmediği
          sürece otomatik olarak yenilenir.
        </li>
        <li>
          Abonelikleri Apple ID hesap ayarlarınızdan yönetebilir veya iptal
          edebilirsiniz.
        </li>
        <li>
          İadeler, fatura sorunları, yenilemeler ve iptaller Apple politikalarına
          göre Apple tarafından yürütülür.
        </li>
        <li>
          Fiyatlar ve sunulan premium özellikler, Apple App Store kuralları ve
          gerekli kullanıcı bildirimleri kapsamında değişebilir.
        </li>
      </ul>

      <h2>8. Apple Standart EULA</h2>
      <p>
        KidTales AI, geçerli hukuk özel bir sözleşme gerektirmediği sürece
        <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener noreferrer">
          Apple Standart Son Kullanıcı Lisans Sözleşmesi
        </a>
        kapsamında size lisanslanır. Bu Şartlar, izin verilen ölçüde Apple
        Standart EULA'yı tamamlar.
      </p>

      <h2>9. Gizlilik</h2>
      <p>
        Uygulamanın kullanımı ayrıca KidTales AI Gizlilik Politikası'na tabidir:
        <a href="https://ibrahimatmaca.github.io/kidtales-privacy" target="_blank" rel="noopener noreferrer">
          https://ibrahimatmaca.github.io/kidtales-privacy
        </a>.
      </p>

      <h2>10. Sonlandırma</h2>
      <p>
        KidTales AI hesap oluşturmayı gerektirmez. Uygulamanın kötüye
        kullanılması, bu Şartların ihlal edilmesi veya yasal, güvenlik ya da
        teknik nedenlerle gerekli olması halinde uygulamaya erişimi askıya
        alabilir veya sınırlandırabiliriz.
      </p>

      <h2>11. Sorumluluğun Sınırlandırılması</h2>
      <p>
        Kanunen izin verilen azami ölçüde uygulama "olduğu gibi" ve "mevcut
        olduğu şekilde" sunulur. Uygulamanın kullanımından veya yapay zekâ
        tarafından üretilen içeriklere güvenilmesinden kaynaklanan dolaylı,
        arızi, özel veya sonuçsal zararlardan sorumlu değiliz.
      </p>

      <h2>12. Uygulanacak Hukuk</h2>
      <p>
        Bu Şartlar, ülkenizde veya bölgenizde geçerli olabilecek zorunlu
        tüketici koruma hakları saklı kalmak üzere Türkiye Cumhuriyeti
        hukukuna tabidir.
      </p>

      <h2>13. Şartlardaki Değişiklikler</h2>
      <p>
        Bu Şartları zaman zaman güncelleyebiliriz. Güncellenmiş Şartlar bu
        sayfada yayımlandığında yürürlüğe girer.
      </p>
      <p>
        En güncel sürüm
        <a href="https://ibrahimatmaca.github.io/kidtales-terms" target="_blank" rel="noopener noreferrer">
          https://ibrahimatmaca.github.io/kidtales-terms
        </a>
        adresinde yayımlanır.
      </p>

      <h2>14. İletişim</h2>
      <p>
        Bu Şartlarla ilgili sorularınız için:
        <br />
        <strong>
          E-posta:
          <a href="mailto:ibrahim.atmaca61@hotmail.com">ibrahim.atmaca61@hotmail.com</a>
        </strong>
      </p>
`;

const KidTalesTerms: React.FC = () => (
  <KidTalesLegalLayout
    englishContent={englishContent}
    turkishContent={turkishContent}
    titleEn="KidTales AI Terms of Use"
    titleTr="KidTales AI Kullanım Şartları"
  />
);

export default KidTalesTerms;
